wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.0
    cli_version: 0.16.6
    framework: huggingface
    huggingface_version: 4.39.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1714470743.0
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 71
      - 83
      - 98
      2:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 71
      - 83
      - 98
      3:
      - 23
      - 24
      4: 3.8.0
      5: 0.16.6
      6: 4.39.3
      8:
      - 5
      13: linux-x86_64
num_users:
  desc: null
  value: 5
data_type:
  desc: null
  value: imagenette
partition:
  desc: null
  value: dirichlet
frac:
  desc: null
  value: 1
beta:
  desc: null
  value: 0.5
data_path_train:
  desc: null
  value: /codespace/imagenet1000/train
data_path_test:
  desc: null
  value: /codespace/imagenet1000/val
com_round:
  desc: null
  value: 5
num_workers:
  desc: null
  value: 4
pretrained_model_name_or_path:
  desc: null
  value: runwayml/stable-diffusion-v1-5
revision:
  desc: null
  value: null
variant:
  desc: null
  value: null
tokenizer_name:
  desc: null
  value: null
instance_data_dir:
  desc: null
  value: ./dog
class_data_dir:
  desc: null
  value: null
instance_prompt:
  desc: null
  value: a photo of sks dog
class_prompt:
  desc: null
  value: null
validation_prompt:
  desc: null
  value: A photo of sks dog in a bucket
num_validation_images:
  desc: null
  value: 4
validation_epochs:
  desc: null
  value: 50
with_prior_preservation:
  desc: null
  value: false
prior_loss_weight:
  desc: null
  value: 1.0
num_class_images:
  desc: null
  value: 100
output_dir:
  desc: null
  value: ./output
seed:
  desc: null
  value: 0
resolution:
  desc: null
  value: 512
center_crop:
  desc: null
  value: false
train_text_encoder:
  desc: null
  value: false
train_batch_size:
  desc: null
  value: 1
sample_batch_size:
  desc: null
  value: 4
num_train_epochs:
  desc: null
  value: 500
max_train_steps:
  desc: null
  value: 500
checkpointing_steps:
  desc: null
  value: 100
checkpoints_total_limit:
  desc: null
  value: null
gradient_accumulation_steps:
  desc: null
  value: 1
gradient_checkpointing:
  desc: null
  value: false
learning_rate:
  desc: null
  value: 0.0001
scale_lr:
  desc: null
  value: false
lr_scheduler:
  desc: null
  value: constant
lr_warmup_steps:
  desc: null
  value: 0
lr_num_cycles:
  desc: null
  value: 1
lr_power:
  desc: null
  value: 1.0
dataloader_num_workers:
  desc: null
  value: 0
use_8bit_adam:
  desc: null
  value: false
adam_beta1:
  desc: null
  value: 0.9
adam_beta2:
  desc: null
  value: 0.999
adam_weight_decay:
  desc: null
  value: 0.01
adam_epsilon:
  desc: null
  value: 1.0e-08
max_grad_norm:
  desc: null
  value: 1.0
push_to_hub:
  desc: null
  value: true
hub_token:
  desc: null
  value: null
hub_model_id:
  desc: null
  value: null
logging_dir:
  desc: null
  value: logs
allow_tf32:
  desc: null
  value: false
report_to:
  desc: null
  value: wandb
mixed_precision:
  desc: null
  value: null
prior_generation_precision:
  desc: null
  value: null
local_rank:
  desc: null
  value: 0
enable_xformers_memory_efficient_attention:
  desc: null
  value: false
pre_compute_text_embeddings:
  desc: null
  value: false
tokenizer_max_length:
  desc: null
  value: null
text_encoder_use_attention_mask:
  desc: null
  value: false
class_labels_conditioning:
  desc: null
  value: null
rank:
  desc: null
  value: 4
